In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [3]:
p152=pd.read_csv("pronostico_dataset.csv", sep=";",index_col="ID")

In [4]:
p152.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6000 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           6000 non-null   float64
 1   systolic_bp   6000 non-null   float64
 2   diastolic_bp  6000 non-null   float64
 3   cholesterol   6000 non-null   float64
 4   prognosis     6000 non-null   object 
dtypes: float64(4), object(1)
memory usage: 281.2+ KB


In [5]:
numeric_column=['age', 'systolic_bp', 'diastolic_bp', 'cholesterol']

In [6]:
p152.describe()

age  systolic_bp  diastolic_bp  cholesterol
count  6000.000000  6000.000000   6000.000000  6000.000000
mean     60.464121   100.694822     90.505547   100.628255
std       8.564392    10.669267      9.648200    10.433915
min      35.164761    69.675429     62.807105    69.967453
25%      54.371941    93.267420     83.641788    93.202373
50%      59.831159   100.119926     89.912429   100.060637
75%      65.809652   107.439501     96.682405   107.250829
max     103.279497   151.699660    133.456382   148.233544

In [7]:
log_=lambda x: np.log(x)
p152_log=p152[numeric_column].apply(log_)
p152_log["prognosis"]=p152["prognosis"]

In [8]:
p152

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                     
0     77.196340    85.288742     80.021878    79.957109     retinopathy
1     63.529850    99.379736     84.852361   110.382411     retinopathy
2     69.003986   111.349455    109.850616   100.828246     retinopathy
3     82.638210    95.056128     79.666851    87.066303     retinopathy
4     78.346286   109.154591     90.713220    92.511770     retinopathy
...         ...          ...           ...          ...             ...
5995  49.611850    94.857639     86.615671   107.643986  no_retinopathy
5996  63.099686   100.039527     93.515186   104.971404     retinopathy
5997  55.562243    98.421446    102.697875   120.875951     retinopathy
5998  63.468956   106.809289     88.060631   106.052213     retinopathy
5999  62.506825    96.900784     86.878033   108.625436  no_retinopathy

[6000 rows x 5 columns]

In [9]:
p152_log

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                    
0     4.346352     4.446042      4.382300     4.381490     retinopathy
1     4.151510     4.598948      4.440913     4.703951     retinopathy
2     4.234164     4.712673      4.699121     4.613419     retinopathy
3     4.414472     4.554468      4.377854     4.466670     retinopathy
4     4.361139     4.692765      4.507703     4.527336     retinopathy
...        ...          ...           ...          ...             ...
5995  3.904230     4.552377      4.461481     4.678829  no_retinopathy
5996  4.144716     4.605565      4.538124     4.653688     retinopathy
5997  4.017504     4.589259      4.631791     4.794765     retinopathy
5998  4.150551     4.671045      4.478026     4.663932     retinopathy
5999  4.135276     4.573688      4.464505     4.687906  no_retinopathy

[6000 rows x 5 columns]

# Model Buidling

## Logistic Model

In [10]:
from sklearn.linear_model import LogisticRegression
normal_model=LogisticRegression()


In [11]:
p152_log

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                    
0     4.346352     4.446042      4.382300     4.381490     retinopathy
1     4.151510     4.598948      4.440913     4.703951     retinopathy
2     4.234164     4.712673      4.699121     4.613419     retinopathy
3     4.414472     4.554468      4.377854     4.466670     retinopathy
4     4.361139     4.692765      4.507703     4.527336     retinopathy
...        ...          ...           ...          ...             ...
5995  3.904230     4.552377      4.461481     4.678829  no_retinopathy
5996  4.144716     4.605565      4.538124     4.653688     retinopathy
5997  4.017504     4.589259      4.631791     4.794765     retinopathy
5998  4.150551     4.671045      4.478026     4.663932     retinopathy
5999  4.135276     4.573688      4.464505     4.687906  no_retinopathy

[6000 rows x 5 columns]

In [12]:
x=p152_log.drop("prognosis", axis=1)
y=p152_log["prognosis"]

In [13]:
log_model=LogisticRegression()
log_model.fit(x,y)
log_model.score(x,y)

0.7421666666666666

In [14]:
x=p152_log.drop(["diastolic_bp","cholesterol","prognosis"], axis=1)
y=p152_log["prognosis"]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=42,test_size=0.2)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [17]:
log_model=LogisticRegression()
log_model.fit(x,y)
log_model.score(x,y)

0.7236666666666667

In [18]:
accuracy_score(log_model.predict(x),y)

0.7236666666666667

In [19]:
confusion_matrix(log_model.predict(x),y)

array([[2070,  815],
       [ 843, 2272]], dtype=int64)

In [20]:
from sklearn.tree import  DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x, y)

DecisionTreeClassifier()

In [21]:
print(model.feature_importances_)

[0.51397277 0.48602723]


In [22]:
x=p152_log.drop("prognosis", axis=1)
y=p152_log["prognosis"]

In [23]:
from sklearn.feature_selection import RFE
model = LogisticRegression(max_iter=400)
rfe = RFE(model,)
fit = rfe.fit(x, y)

In [24]:
fit.n_features_

2

In [25]:
fit.ranking_

array([1, 1, 3, 2])

In [26]:
fit.n_features_

2

In [27]:
fit.support_

array([ True,  True, False, False])

In [30]:
from sklearn.ensemble import RandomForestClassifier

r_forest=RandomForestClassifier(max_depth=4,n_jobs=-1, n_estimators=500)
r_forest.fit(x_train,y_train)
r_forest.score(x_test,y_test)

0.7258333333333333

In [31]:
for i in range(2,10):
    r_forest=RandomForestClassifier(max_depth=i,n_jobs=-1, n_estimators=500)
    r_forest.fit(x_train,y_train)
    print(r_forest.score(x_test,y_test))

0.7158333333333333
0.725
0.7275
0.7316666666666667
0.7283333333333334
0.725
0.7241666666666666
0.7225


In [33]:
for i in range(2,20):
    for j in range(100,1000,100):
            r_forest=RandomForestClassifier(max_depth=i,n_jobs=-1, n_estimators=j)
            r_forest.fit(x_train,y_train)
            print(f"Max_Depth: {i},n_estimator:{j}",r_forest.score(x_test,y_test))

Max_Depth: 2,n_estimator:100 0.7158333333333333
Max_Depth: 2,n_estimator:150 0.7208333333333333
Max_Depth: 2,n_estimator:200 0.7125
Max_Depth: 2,n_estimator:250 0.7166666666666667
Max_Depth: 2,n_estimator:300 0.7183333333333334
Max_Depth: 2,n_estimator:350 0.7166666666666667
Max_Depth: 2,n_estimator:400 0.7166666666666667
Max_Depth: 2,n_estimator:450 0.7166666666666667
Max_Depth: 2,n_estimator:500 0.715
Max_Depth: 2,n_estimator:550 0.7175
Max_Depth: 2,n_estimator:600 0.7133333333333334
Max_Depth: 2,n_estimator:650 0.715
Max_Depth: 2,n_estimator:700 0.7183333333333334
Max_Depth: 2,n_estimator:750 0.7175
Max_Depth: 2,n_estimator:800 0.7166666666666667
Max_Depth: 2,n_estimator:850 0.7141666666666666
Max_Depth: 2,n_estimator:900 0.7166666666666667
Max_Depth: 2,n_estimator:950 0.7175
Max_Depth: 3,n_estimator:100 0.7241666666666666
Max_Depth: 3,n_estimator:150 0.7191666666666666
Max_Depth: 3,n_estimator:200 0.7225
Max_Depth: 3,n_estimator:250 0.7216666666666667
Max_Depth: 3,n_estimator:300 0

In [35]:
p152

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                     
0     77.196340    85.288742     80.021878    79.957109     retinopathy
1     63.529850    99.379736     84.852361   110.382411     retinopathy
2     69.003986   111.349455    109.850616   100.828246     retinopathy
3     82.638210    95.056128     79.666851    87.066303     retinopathy
4     78.346286   109.154591     90.713220    92.511770     retinopathy
...         ...          ...           ...          ...             ...
5995  49.611850    94.857639     86.615671   107.643986  no_retinopathy
5996  63.099686   100.039527     93.515186   104.971404     retinopathy
5997  55.562243    98.421446    102.697875   120.875951     retinopathy
5998  63.468956   106.809289     88.060631   106.052213     retinopathy
5999  62.506825    96.900784     86.878033   108.625436  no_retinopathy

[6000 rows x 5 columns]

In [37]:
p152["prognosis"].replace({"retinopathy":1,"no_retinopathy":0}, inplace=True)

In [38]:
p152

age  systolic_bp  diastolic_bp  cholesterol  prognosis
ID                                                                
0     77.196340    85.288742     80.021878    79.957109          1
1     63.529850    99.379736     84.852361   110.382411          1
2     69.003986   111.349455    109.850616   100.828246          1
3     82.638210    95.056128     79.666851    87.066303          1
4     78.346286   109.154591     90.713220    92.511770          1
...         ...          ...           ...          ...        ...
5995  49.611850    94.857639     86.615671   107.643986          0
5996  63.099686   100.039527     93.515186   104.971404          1
5997  55.562243    98.421446    102.697875   120.875951          1
5998  63.468956   106.809289     88.060631   106.052213          1
5999  62.506825    96.900784     86.878033   108.625436          0

[6000 rows x 5 columns]

In [42]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [43]:
numeric_column

['age', 'systolic_bp', 'diastolic_bp', 'cholesterol']

In [44]:
p152[numeric_column]=scaler.fit_transform(p152[numeric_column])

In [45]:
p152

age  systolic_bp  diastolic_bp  cholesterol  prognosis
ID                                                               
0     1.953859    -1.444088     -1.086684    -1.981315          1
1     0.357992    -0.123270     -0.585981     0.934929          1
2     0.997219     0.998712      2.005212     0.019169          1
3     2.589318    -0.528543     -1.123484    -1.299904          1
4     2.088141     0.792976      0.021526    -0.777959          1
...        ...          ...           ...          ...        ...
5995 -1.267244    -0.547148     -0.403205     0.672453          0
5996  0.307761    -0.061424      0.311964     0.416288          1
5997 -0.572403    -0.213095      1.263795     1.940727          1
5998  0.350881     0.573139     -0.253428     0.519882          1
5999  0.238531    -0.355634     -0.376010     0.766524          0

[6000 rows x 5 columns]

## Neural Network

In [46]:
from keras import Sequential
from keras.layers import Dense

In [47]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=4))
#Second  Hidden Layer
classifier.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [48]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [49]:
x=p152.drop("prognosis", axis=1)
y=p152["prognosis"]

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [60]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=10, epochs=100)

Epoch 1/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5089 - accuracy: 0.7486
Epoch 2/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5082 - accuracy: 0.7496
Epoch 3/100
510/510 [==============================] - 1s 985us/step - loss: 0.5087 - accuracy: 0.7482
Epoch 4/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5085 - accuracy: 0.7492
Epoch 5/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5083 - accuracy: 0.7459
Epoch 6/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5084 - accuracy: 0.7476
Epoch 7/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5084 - accuracy: 0.7461
Epoch 8/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5084 - accuracy: 0.7476
Epoch 9/100
510/510 [==============================] - 0s 945us/step - loss: 0.5084 - accuracy: 0.7490
Epoch 10/100
510/510 [==============================] - 1s 1ms/step - loss: 0.5086 - ac

In [61]:
classifier.evaluate(X_train, y_train)

160/160 [==============================] - 0s 1ms/step - loss: 0.5070 - accuracy: 0.7457


[0.5070299506187439, 0.7456862926483154]

In [62]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

29/29 [==============================] - 0s 997us/step


In [63]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[296 134]
 [100 370]]
