In [178]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [179]:
p152=pd.read_csv("pronostico_dataset.csv", sep=";",index_col="ID")

In [180]:
p152.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6000 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           6000 non-null   float64
 1   systolic_bp   6000 non-null   float64
 2   diastolic_bp  6000 non-null   float64
 3   cholesterol   6000 non-null   float64
 4   prognosis     6000 non-null   object 
dtypes: float64(4), object(1)
memory usage: 281.2+ KB


In [181]:
numeric_column=['age', 'systolic_bp', 'diastolic_bp', 'cholesterol']

In [182]:
p152.describe()

age  systolic_bp  diastolic_bp  cholesterol
count  6000.000000  6000.000000   6000.000000  6000.000000
mean     60.464121   100.694822     90.505547   100.628255
std       8.564392    10.669267      9.648200    10.433915
min      35.164761    69.675429     62.807105    69.967453
25%      54.371941    93.267420     83.641788    93.202373
50%      59.831159   100.119926     89.912429   100.060637
75%      65.809652   107.439501     96.682405   107.250829
max     103.279497   151.699660    133.456382   148.233544

In [183]:
log_=lambda x: np.log(x)
p152_log=p152[numeric_column].apply(log_)
p152_log["prognosis"]=p152["prognosis"]

In [184]:
p152

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                     
0     77.196340    85.288742     80.021878    79.957109     retinopathy
1     63.529850    99.379736     84.852361   110.382411     retinopathy
2     69.003986   111.349455    109.850616   100.828246     retinopathy
3     82.638210    95.056128     79.666851    87.066303     retinopathy
4     78.346286   109.154591     90.713220    92.511770     retinopathy
...         ...          ...           ...          ...             ...
5995  49.611850    94.857639     86.615671   107.643986  no_retinopathy
5996  63.099686   100.039527     93.515186   104.971404     retinopathy
5997  55.562243    98.421446    102.697875   120.875951     retinopathy
5998  63.468956   106.809289     88.060631   106.052213     retinopathy
5999  62.506825    96.900784     86.878033   108.625436  no_retinopathy

[6000 rows x 5 columns]

In [185]:
p152_log

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                    
0     4.346352     4.446042      4.382300     4.381490     retinopathy
1     4.151510     4.598948      4.440913     4.703951     retinopathy
2     4.234164     4.712673      4.699121     4.613419     retinopathy
3     4.414472     4.554468      4.377854     4.466670     retinopathy
4     4.361139     4.692765      4.507703     4.527336     retinopathy
...        ...          ...           ...          ...             ...
5995  3.904230     4.552377      4.461481     4.678829  no_retinopathy
5996  4.144716     4.605565      4.538124     4.653688     retinopathy
5997  4.017504     4.589259      4.631791     4.794765     retinopathy
5998  4.150551     4.671045      4.478026     4.663932     retinopathy
5999  4.135276     4.573688      4.464505     4.687906  no_retinopathy

[6000 rows x 5 columns]

# Model Buidling

## Logistic Model

In [186]:
from sklearn.linear_model import LogisticRegression
normal_model=LogisticRegression()


In [187]:
p152_log

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                    
0     4.346352     4.446042      4.382300     4.381490     retinopathy
1     4.151510     4.598948      4.440913     4.703951     retinopathy
2     4.234164     4.712673      4.699121     4.613419     retinopathy
3     4.414472     4.554468      4.377854     4.466670     retinopathy
4     4.361139     4.692765      4.507703     4.527336     retinopathy
...        ...          ...           ...          ...             ...
5995  3.904230     4.552377      4.461481     4.678829  no_retinopathy
5996  4.144716     4.605565      4.538124     4.653688     retinopathy
5997  4.017504     4.589259      4.631791     4.794765     retinopathy
5998  4.150551     4.671045      4.478026     4.663932     retinopathy
5999  4.135276     4.573688      4.464505     4.687906  no_retinopathy

[6000 rows x 5 columns]

In [188]:
x=p152_log.drop("prognosis", axis=1)
y=p152_log["prognosis"]

In [189]:
log_model=LogisticRegression()
log_model.fit(x,y)
log_model.score(x,y)

0.7421666666666666

In [190]:
x=p152_log.drop(["diastolic_bp","cholesterol","prognosis"], axis=1)
y=p152_log["prognosis"]

In [191]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=42,test_size=0.2)

In [192]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [193]:
log_model=LogisticRegression()
log_model.fit(x,y)
log_model.score(x,y)

0.7236666666666667

In [194]:
accuracy_score(log_model.predict(x),y)

0.7236666666666667

In [195]:
confusion_matrix(log_model.predict(x),y)

array([[2070,  815],
       [ 843, 2272]], dtype=int64)

In [196]:
from sklearn.tree import  DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x, y)

DecisionTreeClassifier()

In [197]:
print(model.feature_importances_)

[0.5186063 0.4813937]


In [198]:
x=p152_log.drop("prognosis", axis=1)
y=p152_log["prognosis"]

In [199]:
from sklearn.feature_selection import RFE
model = LogisticRegression(max_iter=400)
rfe = RFE(model,)
fit = rfe.fit(x, y)

In [200]:
fit.n_features_

2

In [201]:
fit.ranking_

array([1, 1, 3, 2])

In [202]:
fit.n_features_

2

In [203]:
fit.support_

array([ True,  True, False, False])

In [204]:
from sklearn.ensemble import RandomForestClassifier

r_forest=RandomForestClassifier(max_depth=4,n_jobs=-1, n_estimators=500)
r_forest.fit(x_train,y_train)
r_forest.score(x_test,y_test)

0.7266666666666667

In [205]:
for i in range(2,10):
    r_forest=RandomForestClassifier(max_depth=i,n_jobs=-1, n_estimators=500)
    r_forest.fit(x_train,y_train)
    print(r_forest.score(x_test,y_test))

0.7158333333333333
0.7191666666666666
0.7291666666666666
0.7341666666666666
0.7308333333333333
0.7266666666666667
0.7266666666666667
0.7183333333333334


In [206]:
"""for i in range(2,20):
    for j in range(100,1000,100):
            r_forest=RandomForestClassifier(max_depth=i,n_jobs=-1, n_estimators=j)
            r_forest.fit(x_train,y_train)
            print(f"Max_Depth: {i},n_estimator:{j}",r_forest.score(x_test,y_test))"""

'for i in range(2,20):\n    for j in range(100,1000,100):\n            r_forest=RandomForestClassifier(max_depth=i,n_jobs=-1, n_estimators=j)\n            r_forest.fit(x_train,y_train)\n            print(f"Max_Depth: {i},n_estimator:{j}",r_forest.score(x_test,y_test))'

In [207]:
p152

age  systolic_bp  diastolic_bp  cholesterol       prognosis
ID                                                                     
0     77.196340    85.288742     80.021878    79.957109     retinopathy
1     63.529850    99.379736     84.852361   110.382411     retinopathy
2     69.003986   111.349455    109.850616   100.828246     retinopathy
3     82.638210    95.056128     79.666851    87.066303     retinopathy
4     78.346286   109.154591     90.713220    92.511770     retinopathy
...         ...          ...           ...          ...             ...
5995  49.611850    94.857639     86.615671   107.643986  no_retinopathy
5996  63.099686   100.039527     93.515186   104.971404     retinopathy
5997  55.562243    98.421446    102.697875   120.875951     retinopathy
5998  63.468956   106.809289     88.060631   106.052213     retinopathy
5999  62.506825    96.900784     86.878033   108.625436  no_retinopathy

[6000 rows x 5 columns]

In [208]:
p152["prognosis"].replace({"retinopathy":1,"no_retinopathy":0}, inplace=True)

In [209]:
p152

age  systolic_bp  diastolic_bp  cholesterol  prognosis
ID                                                                
0     77.196340    85.288742     80.021878    79.957109          1
1     63.529850    99.379736     84.852361   110.382411          1
2     69.003986   111.349455    109.850616   100.828246          1
3     82.638210    95.056128     79.666851    87.066303          1
4     78.346286   109.154591     90.713220    92.511770          1
...         ...          ...           ...          ...        ...
5995  49.611850    94.857639     86.615671   107.643986          0
5996  63.099686   100.039527     93.515186   104.971404          1
5997  55.562243    98.421446    102.697875   120.875951          1
5998  63.468956   106.809289     88.060631   106.052213          1
5999  62.506825    96.900784     86.878033   108.625436          0

[6000 rows x 5 columns]

In [210]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [211]:
numeric_column

['age', 'systolic_bp', 'diastolic_bp', 'cholesterol']

In [212]:
p152[numeric_column]=scaler.fit_transform(p152[numeric_column])

In [213]:
p152

age  systolic_bp  diastolic_bp  cholesterol  prognosis
ID                                                               
0     1.953859    -1.444088     -1.086684    -1.981315          1
1     0.357992    -0.123270     -0.585981     0.934929          1
2     0.997219     0.998712      2.005212     0.019169          1
3     2.589318    -0.528543     -1.123484    -1.299904          1
4     2.088141     0.792976      0.021526    -0.777959          1
...        ...          ...           ...          ...        ...
5995 -1.267244    -0.547148     -0.403205     0.672453          0
5996  0.307761    -0.061424      0.311964     0.416288          1
5997 -0.572403    -0.213095      1.263795     1.940727          1
5998  0.350881     0.573139     -0.253428     0.519882          1
5999  0.238531    -0.355634     -0.376010     0.766524          0

[6000 rows x 5 columns]

## Neural Network

In [214]:
from keras import Sequential
from keras.layers import Dense

In [215]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(4, activation='tanh', kernel_initializer='random_normal', input_dim=4))
#Second  Hidden Layer
classifier.add(Dense(6, activation='tanh', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

In [216]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

In [217]:
from sklearn.model_selection import train_test_split
x=p152.drop("prognosis", axis=1)
y=p152["prognosis"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

In [218]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=50, epochs=70)

Epoch 1/70
102/102 [==============================] - 0s 1ms/step - loss: 0.6820 - accuracy: 0.6678
Epoch 2/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5951 - accuracy: 0.7314
Epoch 3/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5329 - accuracy: 0.7424
Epoch 4/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5217 - accuracy: 0.7451
Epoch 5/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5204 - accuracy: 0.7443
Epoch 6/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5201 - accuracy: 0.7427
Epoch 7/70
102/102 [==============================] - 0s 974us/step - loss: 0.5197 - accuracy: 0.7433
Epoch 8/70
102/102 [==============================] - 0s 928us/step - loss: 0.5195 - accuracy: 0.7427
Epoch 9/70
102/102 [==============================] - 0s 1ms/step - loss: 0.5193 - accuracy: 0.7433
Epoch 10/70
102/102 [==============================] - 0s 959us/step - loss: 0.5192 - accuracy: 

In [219]:
classifier.evaluate(X_test, y_test)

29/29 [==============================] - 0s 851us/step - loss: 0.5123 - accuracy: 0.7500


[0.5123162865638733, 0.75]

In [220]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

29/29 [==============================] - 0s 609us/step


In [221]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[323 114]
 [111 352]]


### Neural Network Gridsearch

In [222]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [223]:
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=4))
#Second  Hidden Layer
	model.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
	model.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [224]:
# Grid Search Parameter
batch_size = [10, 35,50,80, 70]
epochs = [10, 30, 70,60,80]
param_grid = dict(batch_size=batch_size, epochs=epochs)

In [225]:
model = Sequential()
model.add(Dense(4, activation='relu', kernel_initializer='random_normal', input_dim=4))
#Second  Hidden Layer
model.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
#Output Layer
model.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))
	# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [226]:
model = KerasClassifier(model=model)

In [227]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train,y_train)

INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpysf1jrtk\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmptjpixfh3\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpnnu4jg3m\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpliovkfgh\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpuf1gc2_o\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmp85d1gx20\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpro6x0k_e\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmprtvgs_df\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpjxcjhdcq\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmppivz7uja\assets
INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmpfa860ofn\assets
INFO:tensorflow:Assets written to: C:\Users

In [228]:
grid.best_estimator_

KerasClassifier(
	model=<keras.engine.sequential.Sequential object at 0x00000225A69EFD60>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=10
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=70
	class_weight=None
)

In [229]:
grid.best_params_

{'batch_size': 10, 'epochs': 70}

In [230]:
grid.best_score_

0.7490196078431373

In [231]:
n_model=grid.best_estimator_

In [232]:
n_model

KerasClassifier(
	model=<keras.engine.sequential.Sequential object at 0x00000225A69EFD60>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=10
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=70
	class_weight=None
)

In [233]:
n_model.score(X_test,y_test)

90/90 [==============================] - 0s 668us/step


0.7566666666666667

In [234]:
x=p152.drop("prognosis", axis=1)
y=p152["prognosis"]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

In [235]:
n_model.score(X_test,y_test)

90/90 [==============================] - 0s 649us/step


0.7566666666666667

In [236]:
import pickle
pickle.dump(n_model, open('N_model.sav', 'wb'))

INFO:tensorflow:Assets written to: C:\Users\acer\AppData\Local\Temp\tmp0wkdvbx1\assets


In [237]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [238]:
confusion_matrix(y_test,n_model.predict(X_test))

90/90 [==============================] - 0s 710us/step


array([[315, 122],
       [ 97, 366]], dtype=int64)

### NN for Categorised data

In [239]:
p152_cat=pd.read_csv("p152_cate.csv", index_col="ID")

In [240]:
p152_cat.head(2)

age_Cate  prognosis diastolic_bp      cholesterol systolic_bp
ID                                                              
0     75-85          1    Normal_bp          optimal   Normal_bp
1     55-65          1    Normal_bp  Borderline_high   Normal_bp

In [241]:
p152_cat2=pd.get_dummies(data=p152_cat, columns=["age_Cate","diastolic_bp","cholesterol","systolic_bp"])

In [242]:
p152_cat2["prognosis"]=p152_cat["prognosis"]

In [243]:
p152_cat2

prognosis  age_Cate_100-105  age_Cate_35-45  age_Cate_45-55  \
ID                                                                  
0             1                 0               0               0   
1             1                 0               0               0   
2             1                 0               0               0   
3             1                 0               0               0   
4             1                 0               0               0   
...         ...               ...             ...             ...   
5995          0                 0               0               1   
5996          1                 0               0               0   
5997          1                 0               0               0   
5998          1                 0               0               0   
5999          0                 0               0               0   

      age_Cate_55-65  age_Cate_65-75  age_Cate_75-85  age_Cate_85-95  \
ID                                                                     
0                  0               0               1               0   
1                  1               0               0               0   
2                  0               1               0               0   
3                  0               0               1               0   
4                  0               0               1               0   
...              ...             ...             ...             ...   
5995               0               0               0               0   
5996               1               0               0               0   
5997               1               0               0               0   
5998               1               0               0               0   
5999               1               0               0               0   

      age_Cate_95-100  diastolic_bp_Hypertensive_crisis  \
ID                                                        
0                   0                                 0   
1                   0                                 0   
2                   0                                 0   
3                   0                                 0   
4                   0                                 0   
...               ...                               ...   
5995                0                                 0   
5996                0                                 0   
5997                0                                 0   
5998                0                                 0   
5999                0                                 0   

      diastolic_bp_Normal_bp  diastolic_bp_Stage_1_hypertension  \
ID                                                                
0                          1                                  0   
1                          1                                  0   
2                          0                                  0   
3                          1                                  0   
4                          0                                  1   
...                      ...                                ...   
5995                       1                                  0   
5996                       0                                  1   
5997                       0                                  0   
5998                       1                                  0   
5999                       1                                  0   

      diastolic_bp_Stage_2_hypertension  cholesterol_Borderline_high  \
ID                                                                     
0                                     0                            0   
1                                     0                            1   
2                                     1                            0   
3                                     0                            0   
4                                     0                            0   
...                        

In [244]:
x.shape

(6000, 4)

In [245]:
x=p152_cat2.drop("prognosis", axis=1)
y=p152_cat2["prognosis"]

In [246]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

In [247]:
# Grid Search Parameter
batch_size = [10, 35,50,80, 70]
epochs = [10, 30, 70,60,80]
param_grid = dict(batch_size=batch_size, epochs=epochs)

In [248]:
def create_model():
	# create model
	model = Sequential()
	model.add(Dense(19, activation='relu', kernel_initializer='random_normal', input_dim=19))
    #Second  Hidden Layer
	model.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
    #Second  Hidden Layer
	model.add(Dense(4, activation='relu', kernel_initializer='random_normal'))
    #Output Layer
	model.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))
	# Compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [249]:
model = KerasClassifier(model=create_model)

In [250]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train,y_train)

In [ ]:
grid_result.best_params_

{'batch_size': 70, 'epochs': 70}

In [ ]:
grid_result.best_score_

0.7090196078431372

In [ ]:
cate_nn=grid_result.best_estimator_

In [ ]:
cate_nn.score(X_test,y_test)

13/13 [==============================] - 0s 688us/step


0.7044444444444444